name: Build test
on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'
  push:
    branches:
      - 'cibuild'
      - 'master'
      - 'next'
      - 'stable/**'
    paths-ignore:
      - 'Documentation/**'
      - 'lib*/docs/**'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-s390x:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v1
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: s390x
          distro: ubuntu_latest
          githubToken: "${{ github.token }}"
          env: |
            COMPILER: gcc
            COMPILER_VERSION: 10
            SANITIZE: no
            QEMU_USER: 1
          install: |
            # name: Ubuntu setup
            pwd
            ls -l
            .github/workflows/cibuild-setup-ubuntu.sh
          run: |
            git config --global --add safe.directory "$PWD"
            # Configure & Make
            .github/workflows/cibuild.sh CONFIGURE MAKE
            # Check
            .github/workflows/cibuild.sh CHECK
